name: PSX Daily Auto Reports

on:
  schedule:
    # صبح 09:00 AM PKT (04:00 UTC)
    - cron: '0 4 * * 1-5'
    # شام 04:20 PM PKT (11:20 UTC)
    - cron: '20 11 * * 1-5'
  workflow_dispatch:

jobs:
  send-email-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 yfinance pandas

      - name: Run Email Script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASS: ${{ secrets.SENDER_PASS }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python send_report.py
